language: python
python:
    - "3.6"
env:
    - DJANGO_PACKAGE="Django==2.0"
    - DJANGO_PACKAGE="Django==2.1"
install: pip install $DJANGO_PACKAGE
script: PYTHONPATH=. DJANGO_SETTINGS_MODULE=tests.test_settings django-admin test
matrix:
notifications:
    email:
        - dev@jamesturk.net
